# Site
repository: nakkasoft/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 나 상엽
title: Sepcialist
email: nakka12@empal.com
website: nakkasoft.github.io/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: nakkasoft
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sangyeob-na-16645375
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: nakkasoft.blog
  icon: fas fa-globe
  url: https://nakkasoft.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    안녕하세요. 12년차 SW개발자 입니다.
    Native/Web base의 TV Application 개발을 거쳐 지금은 차량용 Main Display인 Full LCD Display의 계기판 HMI 개발 및 리딩하는 테크니컬 리더로서의 업무를 수행하고 있습니다.
    Native <mark>C</mark>, <mark>C++</mark>, <mark>Python</mark>, <mark>Java Script</mark>에 대한 Skill을 보유 하고 있습니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 전국 카톨릭 성지 알림
#        link: github.com/nakkasoft
        # link_text: Project Website
#        additional_links:
#          - title:  nakkasoft/modern-resume
#            icon: fab fa-github
#            url: github.com/nakkasoft/modern-resume
#          # - title:  Github page for project (eg. nakkasoft/modern-resume)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. nakkasoft.github.io/modern-resume)
        quote: >
          전국에 있는 카톨릭 성지 알리미
        description: | # this will include new lines to allow paragraphs
          카톨릭 성지 관광화를 목적으로 개발한 안드로이드 Application.
          GPS 기반으로 현재 위치를 기준으로 반경 내에 있는 카톨릭 성지를 알려 줌.

      - layout: left
        title: 더하기빼기
        link: github.com/nakkasoft
        # link_text: Project Website
#        additional_links:
#          - title:  nakkasoft/modern-resume
#            icon: fab fa-github
#            url: github.com/nakkasoft/modern-resume
#          # - title:  Github page for project (eg. nakkasoft/modern-resume)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. nakkasoft.github.io/modern-resume)
        quote: >
          유아/초등 대상 더하기 빼기 게임
        description: | # this will include new lines to allow paragraphs
          유아 부터 초등 학생까지 더하기 뺴기가 가능한 아동을 대상으로 더하기 빼기 게임을 제공함.
          3가지 모드의 게임이 존재 하며, 게임을 통해 암산 능력을 키워줌.
          현재 개발 중이며, 올해 8월 Release예정.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LG전자
        link: lge.com
        # link_text: boringcompany.com
        sub_title: 선임연구원
        caption: 2012년 3월 - 현재
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Enyo Framework 기반의 Java Script Application 개발. (~2015년 12월), C/JavaScript
          차량용 계기판 UI Application 개발, C++/Python/RESTful API

      - layout: left
        title: LG디스플레이
        link: lgdisplay.com
        # link_text: boringcompany.com
        sub_title: 연구원
        caption: 2011년 6월 - 2012년 3월
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            TV용 Twitter Native Application 개발

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 아주대학교
        caption: 2003 - 2012
        sub_title: 정보 및 컴퓨터 공학부
        description: | # this will include new lines to allow paragraphs

  - title: 못 다한 이야기
    layout: text
    content: | # this will include new lines to allow paragraphs
      모든 SW의 개발 Process 대응 <br>
        다년간의 개발을 통해서 고객의 요구 사항으로 부터 정의 되는 Spec분석 및 작성, 요구 기능 개발, Issue 대응 가능. <br><br>

      불편함을 개선 한다. - 현재에 안주 하지 않고, 필요한 SW 개발.<br>
       Can Simulator : 차량용 CAN Signal 생성기.<br>
       Jira Issue 생성기 : web 접속 없이 PC에서 바로 Jira Issue 생성.<br>
       Remote PC 접속기 : 다수의 Remote PC 접속 관리.<br>
       서버 사용량 통계 제공 : Jenkins를 통한 스케쥴링으로 나온 서버 사용량 Data를 web page를 통해 제공.<br>


#      Look at this cool image  
#      ![Trees](/resume/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-minimal
